# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kasper-ubuntu/Documents/APPL_project_tetris/vhdl/sindri_constraints.xdc

# XDC: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/constrs_1/imports/vhdl/sindri_constraints.xdc

# Block Designs: bd/com_side/com_side.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side || ORIG_REF_NAME==com_side} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_0/com_side_simple_button_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_0 || ORIG_REF_NAME==com_side_simple_button_fsm_0_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_1/com_side_simple_button_fsm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_1 || ORIG_REF_NAME==com_side_simple_button_fsm_0_1} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_2/com_side_simple_button_fsm_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_2 || ORIG_REF_NAME==com_side_simple_button_fsm_0_2} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_2_0/com_side_simple_button_fsm_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_2_0 || ORIG_REF_NAME==com_side_simple_button_fsm_2_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_xlconcat_0_0/com_side_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_0_0 || ORIG_REF_NAME==com_side_xlconcat_0_0} -quiet] -quiet

# Block Designs: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_vga_gen_0_0/top_level_vga_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_vga_gen_0_0 || ORIG_REF_NAME==top_level_vga_gen_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_clocking_0_0/top_level_clocking_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_clocking_0_0 || ORIG_REF_NAME==top_level_clocking_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_serialiser_0_0/top_level_serialiser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_serialiser_0_0 || ORIG_REF_NAME==top_level_serialiser_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_serialiser_0_1/top_level_serialiser_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_serialiser_0_1 || ORIG_REF_NAME==top_level_serialiser_0_1} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_serialiser_1_0/top_level_serialiser_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_serialiser_1_0 || ORIG_REF_NAME==top_level_serialiser_1_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_TMDS_encoder_0_0/top_level_TMDS_encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_TMDS_encoder_0_0 || ORIG_REF_NAME==top_level_TMDS_encoder_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_TMDS_encoder_0_1/top_level_TMDS_encoder_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_TMDS_encoder_0_1 || ORIG_REF_NAME==top_level_TMDS_encoder_0_1} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_TMDS_encoder_0_2/top_level_TMDS_encoder_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_TMDS_encoder_0_2 || ORIG_REF_NAME==top_level_TMDS_encoder_0_2} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_output_diff_0_0/top_level_output_diff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_output_diff_0_0 || ORIG_REF_NAME==top_level_output_diff_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_output_diff_0_1/top_level_output_diff_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_output_diff_0_1 || ORIG_REF_NAME==top_level_output_diff_0_1} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_output_diff_0_2/top_level_output_diff_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_output_diff_0_2 || ORIG_REF_NAME==top_level_output_diff_0_2} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_output_diff_0_3/top_level_output_diff_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_output_diff_0_3 || ORIG_REF_NAME==top_level_output_diff_0_3} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_draw_box_0_0/top_level_draw_box_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_draw_box_0_0 || ORIG_REF_NAME==top_level_draw_box_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_color_lookup_0_0/top_level_color_lookup_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_color_lookup_0_0 || ORIG_REF_NAME==top_level_color_lookup_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_row_fetcher_0_0/top_level_row_fetcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_row_fetcher_0_0 || ORIG_REF_NAME==top_level_row_fetcher_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_blk_mem_gen_0_0/top_level_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_blk_mem_gen_0_0 || ORIG_REF_NAME==top_level_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.srcs/sources_1/bd/top_level/ip/top_level_color_fetcher_0_0/top_level_color_fetcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_color_fetcher_0_0 || ORIG_REF_NAME==top_level_color_fetcher_0_0} -quiet] -quiet

# XDC: /home/kasper-ubuntu/Documents/APPL_project_tetris/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/com_side_ooc.xdc

# XDC: /home/kasper-ubuntu/Documents/APPL_project_tetris/frame_gen/frame_gen.gen/sources_1/bd/top_level/top_level_ooc.xdc
