# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kasper-ubuntu/Documents/AAPL_project/vhdl/sindri_constraints.xdc

# Block Designs: bd/block_test/block_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test || ORIG_REF_NAME==block_test} -quiet] -quiet

# IP: bd/block_test/ip/block_test_Sindri_QLink_top_0_0/block_test_Sindri_QLink_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_Sindri_QLink_top_0_0 || ORIG_REF_NAME==block_test_Sindri_QLink_top_0_0} -quiet] -quiet

# IP: bd/block_test/ip/block_test_blk_mem_gen_0_0/block_test_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_blk_mem_gen_0_0 || ORIG_REF_NAME==block_test_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/block_test/ip/block_test_xlconstant_0_0/block_test_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_xlconstant_0_0 || ORIG_REF_NAME==block_test_xlconstant_0_0} -quiet] -quiet

# IP: bd/block_test/ip/block_test_enable_0_0/block_test_enable_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_enable_0_0 || ORIG_REF_NAME==block_test_enable_0_0} -quiet] -quiet

# IP: bd/block_test/ip/block_test_enable_0_1/block_test_enable_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_enable_0_1 || ORIG_REF_NAME==block_test_enable_0_1} -quiet] -quiet

# IP: bd/block_test/ip/block_test_xlslice_0_0/block_test_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_xlslice_0_0 || ORIG_REF_NAME==block_test_xlslice_0_0} -quiet] -quiet

# IP: bd/block_test/ip/block_test_enable_0_2/block_test_enable_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_enable_0_2 || ORIG_REF_NAME==block_test_enable_0_2} -quiet] -quiet

# XDC: /home/kasper-ubuntu/Documents/AAPL_project/QLink_2020/QLink_2020.gen/sources_1/bd/block_test/ip/block_test_blk_mem_gen_0_0/block_test_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/kasper-ubuntu/Documents/AAPL_project/QLink_2020/QLink_2020.gen/sources_1/bd/block_test/block_test_ooc.xdc
