# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jacob/shared/Semester8/AAPL/project/vhdl/sindri_constraints.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/frame_gen/frame_gen.srcs/constrs_1/imports/vhdl/sindri_constraints.xdc

# Block Designs: bd/com_side/com_side.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side || ORIG_REF_NAME==com_side} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_0/com_side_simple_button_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_0 || ORIG_REF_NAME==com_side_simple_button_fsm_0_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_1/com_side_simple_button_fsm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_1 || ORIG_REF_NAME==com_side_simple_button_fsm_0_1} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_2/com_side_simple_button_fsm_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_2 || ORIG_REF_NAME==com_side_simple_button_fsm_0_2} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_2_0/com_side_simple_button_fsm_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_2_0 || ORIG_REF_NAME==com_side_simple_button_fsm_2_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_xlconcat_0_0/com_side_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_0_0 || ORIG_REF_NAME==com_side_xlconcat_0_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_xlconcat_1_0/com_side_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_1_0 || ORIG_REF_NAME==com_side_xlconcat_1_0} -quiet] -quiet

# Block Designs: bd/main_top/main_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_top || ORIG_REF_NAME==main_top} -quiet] -quiet

# IP: bd/main_top/ip/main_top_top_level_0_1/main_top_top_level_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_top_top_level_0_1 || ORIG_REF_NAME==main_top_top_level_0_1} -quiet] -quiet

# IP: bd/main_top/ip/main_top_com_side_wrapper_0_2/main_top_com_side_wrapper_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_top_com_side_wrapper_0_2 || ORIG_REF_NAME==main_top_com_side_wrapper_0_2} -quiet] -quiet

# Block Designs: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0 || ORIG_REF_NAME==block_test_inst_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_Sindri_QLink_top_0_0/block_test_inst_0_Sindri_QLink_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0 || ORIG_REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_blk_mem_gen_0_0/block_test_inst_0_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_blk_mem_gen_0_0 || ORIG_REF_NAME==block_test_inst_0_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_enable_0_0/block_test_inst_0_enable_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_enable_0_0 || ORIG_REF_NAME==block_test_inst_0_enable_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_reset_0_0/block_test_inst_0_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_reset_0_0 || ORIG_REF_NAME==block_test_inst_0_reset_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_write_enable_0/block_test_inst_0_write_enable_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_write_enable_0 || ORIG_REF_NAME==block_test_inst_0_write_enable_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_mux_addr_0/block_test_inst_0_mux_addr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_mux_addr_0 || ORIG_REF_NAME==block_test_inst_0_mux_addr_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_mux_data_0/block_test_inst_0_mux_data_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_mux_data_0 || ORIG_REF_NAME==block_test_inst_0_mux_data_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_mux_wen_0/block_test_inst_0_mux_wen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_mux_wen_0 || ORIG_REF_NAME==block_test_inst_0_mux_wen_0} -quiet] -quiet

# Block Designs: bd/com_side/com_side.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side || ORIG_REF_NAME==com_side} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_0/com_side_simple_button_fsm_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_0 || ORIG_REF_NAME==com_side_simple_button_fsm_0_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_1/com_side_simple_button_fsm_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_1 || ORIG_REF_NAME==com_side_simple_button_fsm_0_1} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_0_2/com_side_simple_button_fsm_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_2 || ORIG_REF_NAME==com_side_simple_button_fsm_0_2} -quiet] -quiet

# IP: bd/com_side/ip/com_side_simple_button_fsm_2_0/com_side_simple_button_fsm_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_2_0 || ORIG_REF_NAME==com_side_simple_button_fsm_2_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_xlconcat_0_0/com_side_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_0_0 || ORIG_REF_NAME==com_side_xlconcat_0_0} -quiet] -quiet

# IP: bd/com_side/ip/com_side_xlconcat_1_0/com_side_xlconcat_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_1_0 || ORIG_REF_NAME==com_side_xlconcat_1_0} -quiet] -quiet

# IP: bd/main_top/ip/main_top_xlconstant_1_0/main_top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_top_xlconstant_1_0 || ORIG_REF_NAME==main_top_xlconstant_1_0} -quiet] -quiet

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/com_side_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/com_side_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/main_top_ooc.xdc
