# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kasper-ubuntu/Documents/AAPL_project/vhdl/sindri_constraints.xdc

# Block Designs: bd/button_LED/button_LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==button_LED || ORIG_REF_NAME==button_LED} -quiet] -quiet

# IP: bd/button_LED/ip/button_LED_xlconstant_0_0/button_LED_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==button_LED_xlconstant_0_0 || ORIG_REF_NAME==button_LED_xlconstant_0_0} -quiet] -quiet

# IP: bd/button_LED/ip/button_LED_simple_button_fsm_0_0/button_LED_simple_button_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==button_LED_simple_button_fsm_0_0 || ORIG_REF_NAME==button_LED_simple_button_fsm_0_0} -quiet] -quiet

# IP: bd/button_LED/ip/button_LED_simple_button_fsm_0_1/button_LED_simple_button_fsm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==button_LED_simple_button_fsm_0_1 || ORIG_REF_NAME==button_LED_simple_button_fsm_0_1} -quiet] -quiet

# IP: bd/button_LED/ip/button_LED_simple_button_fsm_1_0/button_LED_simple_button_fsm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==button_LED_simple_button_fsm_1_0 || ORIG_REF_NAME==button_LED_simple_button_fsm_1_0} -quiet] -quiet

# XDC: /home/kasper-ubuntu/Documents/AAPL_project/vhdl/pl_side/pl_side.gen/sources_1/bd/button_LED/button_LED_ooc.xdc
