# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/main_top/ip/main_top_top_level_0_1/main_top_top_level_0_1.xci
# IP: The module: 'main_top_top_level_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_blk_mem_gen_0_0/top_level_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_blk_mem_gen_0_0 || ORIG_REF_NAME==top_level_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_blk_mem_gen_0_0/top_level_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_top_top_level_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/main_top/ip/main_top_top_level_0_1/main_top_top_level_0_1.xci
# IP: The module: 'main_top_top_level_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_blk_mem_gen_0_0/top_level_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_blk_mem_gen_0_0 || ORIG_REF_NAME==top_level_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_blk_mem_gen_0_0/top_level_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/main_top/ip/main_top_top_level_0_1/src/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_top_top_level_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
