# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/main_top/ip/main_top_com_side_wrapper_0_2/main_top_com_side_wrapper_0_2.xci
# IP: The module: 'main_top_com_side_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0 || ORIG_REF_NAME==block_test_inst_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_Sindri_QLink_top_0_0/block_test_inst_0_Sindri_QLink_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0 || ORIG_REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_blk_mem_gen_0_0/block_test_inst_0_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_blk_mem_gen_0_0 || ORIG_REF_NAME==block_test_inst_0_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_enable_0_0/block_test_inst_0_enable_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_enable_0_0 || ORIG_REF_NAME==block_test_inst_0_enable_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_reset_0_0/block_test_inst_0_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_reset_0_0 || ORIG_REF_NAME==block_test_inst_0_reset_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_write_enable_0/block_test_inst_0_write_enable_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_write_enable_0 || ORIG_REF_NAME==block_test_inst_0_write_enable_0} -quiet] -quiet

# Block Designs: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/com_side.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side || ORIG_REF_NAME==com_side} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_0/com_side_simple_button_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_0 || ORIG_REF_NAME==com_side_simple_button_fsm_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_1/com_side_simple_button_fsm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_1 || ORIG_REF_NAME==com_side_simple_button_fsm_0_1} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_2/com_side_simple_button_fsm_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_2 || ORIG_REF_NAME==com_side_simple_button_fsm_0_2} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_2_0/com_side_simple_button_fsm_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_2_0 || ORIG_REF_NAME==com_side_simple_button_fsm_2_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_xlconcat_0_0/com_side_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_0_0 || ORIG_REF_NAME==com_side_xlconcat_0_0} -quiet] -quiet

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/com_side_ooc.xdc

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/main_top/ip/main_top_com_side_wrapper_0_2/main_top_com_side_wrapper_0_2.xci
# IP: The module: 'main_top_com_side_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0 || ORIG_REF_NAME==block_test_inst_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_Sindri_QLink_top_0_0/block_test_inst_0_Sindri_QLink_top_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0 || ORIG_REF_NAME==block_test_inst_0_Sindri_QLink_top_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_blk_mem_gen_0_0/block_test_inst_0_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_blk_mem_gen_0_0 || ORIG_REF_NAME==block_test_inst_0_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_enable_0_0/block_test_inst_0_enable_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_enable_0_0 || ORIG_REF_NAME==block_test_inst_0_enable_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_reset_0_0/block_test_inst_0_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_reset_0_0 || ORIG_REF_NAME==block_test_inst_0_reset_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/ip/block_test_inst_0_write_enable_0/block_test_inst_0_write_enable_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_test_inst_0_write_enable_0 || ORIG_REF_NAME==block_test_inst_0_write_enable_0} -quiet] -quiet

# Block Designs: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/com_side.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side || ORIG_REF_NAME==com_side} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_0/com_side_simple_button_fsm_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_0 || ORIG_REF_NAME==com_side_simple_button_fsm_0_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_1/com_side_simple_button_fsm_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_1 || ORIG_REF_NAME==com_side_simple_button_fsm_0_1} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_0_2/com_side_simple_button_fsm_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_0_2 || ORIG_REF_NAME==com_side_simple_button_fsm_0_2} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_simple_button_fsm_2_0/com_side_simple_button_fsm_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_simple_button_fsm_2_0 || ORIG_REF_NAME==com_side_simple_button_fsm_2_0} -quiet] -quiet

# IP: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.srcs/sources_1/bd/com_side/ip/com_side_xlconcat_0_0/com_side_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==com_side_xlconcat_0_0 || ORIG_REF_NAME==com_side_xlconcat_0_0} -quiet] -quiet

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/bd/block_test_inst_0/block_test_inst_0_ooc.xdc

# XDC: /home/jacob/shared/Semester8/AAPL/project/QLink_2020/QLink_2020.gen/sources_1/bd/com_side/com_side_ooc.xdc
